<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>org.GraphDefined.Vanaheimr.Hermod.HTTP3</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\libs\Hermod\Hermod\Hermod.csproj" />
    <ProjectReference Include="..\Http3.Qpack\Http3.Qpack.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Http3.Tests" />
  </ItemGroup>

</Project>
