<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>org.GraphDefined.Vanaheimr.Hermod.HTTP3.Qpack</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\libs\Hermod\Hermod\Hermod.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Http3.Tests" />
  </ItemGroup>

</Project>
