<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>org.GraphDefined.Vanaheimr.Hermod.HTTP3.Tests</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <!-- Gemeinsame Einstellungen kommen aus Directory.Build.props -->
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Quic.Core\Quic.Core.csproj" />
    <ProjectReference Include="..\..\src\Quic\Quic.csproj" />
    <ProjectReference Include="..\..\src\Quic.Tls\Quic.Tls.csproj" />
    <ProjectReference Include="..\..\src\Http3.Qpack\Http3.Qpack.csproj" />
    <ProjectReference Include="..\..\src\Http3\Http3.csproj" />
  </ItemGroup>

</Project>